web_main:
    path: /
    defaults:
        _controller: SisesWebClientBundle:Web:index

view_partials:
    path: /views/{name}
    defaults:
        _controller: SisesWebClientBundle:Web:view
    options:
        expose: true