web_main:
    path: /
    defaults:
        _controller: SisesWebClientBundle:Web:index

view_partials:
    path: /views/{name}
    defaults:
        _controller: SisesWebClientBundle:Web:view
    requirements:
        name: .+
    options:
        expose: true

view_menu:
    path: /menu
    defaults:
        _controller: SisesWebClientBundle:Web:menu