imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator:
        fallback: %locale%
    secret: %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines:
            - twig
    default_locale: %locale%
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true

twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles: [ ]
    filters:
        cssrewrite: ~
        scssphp:
            apply_to: '\.scss$'
            formatter: 'compressed'
            preserve_comments: false

doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%_%kernel.environment%
        user: %database_user%
        password: %database_password%
        charset: UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, xml, html ], fallback_format: ~, prefer_extension: true }
            - { path: ^/,    priorities: [ html, js, '*/*'], fallback_format: ~, prefer_extension: true }
    body_listener: true


#jms_di_extra:
#    locations:
#        all_bundles: false
#        bundles: [FooBundle, AcmeBlogBundle]
#        directories: ["%kernel.root_dir%/../src"]