imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: security_prod.yml }

framework:
    translator:
        fallback: %locale%
    secret: %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
        strict_requirements: ~
    form: ~
    csrf_protection: false
    validation:
        enable_annotations: true
    templating:
        engines:
            - twig
    default_locale: %locale%
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true

twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        web_uploads: %kernel.root_dir%/../web/uploads/documentable
        version: %version%
        app_name: Sistema de Información Kabala
        app_shortname: SIK

assetic:
    debug: %kernel.debug%
    use_controller: %use_assetic_controller%
    bundles: [ SisesWebClientBundle, SisesApplicationBundle ]
    filters:
        scss:
            sass: %sass_bin%
            apply_to: '\.scss$'
        autoprefixer: ~
        cssrewrite: ~


doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        charset: UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                default_repository_class: Concepto\Sises\ApplicationBundle\Entity\EntityRepository
                auto_mapping: true
                dql:
                    datetime_functions:
                        date: Concepto\Sises\ApplicationBundle\Query\Functions\DateFunction

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, xml, html ], fallback_format: ~, prefer_extension: true }
            - { path: ^/,    priorities: [ html, pdf, js, css, scss, '*/*'], fallback_format: ~, prefer_extension: true }
    body_listener: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Concepto\Sises\ApplicationBundle\Entity\Seguridad\Usuario


jms_di_extra:
    locations:
        all_bundles: false
        bundles: [SisesApplicationBundle]
        directories: ["%kernel.root_dir%/../src"]

oneup_uploader:
    mappings:
        documentable:
            frontend: plupload