imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
#    session:
#        handler_id: session.handler.native_file
#        save_path: "%kernel.root_dir%/../sessions"

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: "%use_assetic_controller%"

#swiftmailer:
#    delivery_address: me@example.com
bazinga_faker:
    orm: doctrine
    entities:
      Concepto\Sises\ApplicationBundle\Entity\Persona:
        number: 100
        custom_formatters:
          nombre: { method: firstName }
          apellidos: { method: lastName }
          documento: { method: numerify, parameters: [ '###########' ] }
