fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

concepto_sises:
    type: rest
    resource: @SisesApplicationBundle/Resources/config/routing.yml
    options:
        expose: true

concpeto_sises_web:
    resource: @SisesWebClientBundle/Resources/config/routing.yml