fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

concepto_pdf:
    path: /pdf/planilla/{id}/{date}.{_format}
    defaults:  { _controller: SisesApplicationBundle:PDF\PDF:planilla, _format: pdf }
    requirements:
        _format: pdf

concepto_sises:
    type: rest
    resource: @SisesApplicationBundle/Resources/config/routing.yml
    options:
        expose: true

concpeto_sises_web:
    resource: @SisesWebClientBundle/Resources/config/routing.yml

oneup_uploader:
    resource: .
    type: uploader
    options:
        expose: true
