fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

concepto_sises:
    resource: @SisesApplicationBundle/Resources/config/routing.yml

concpeto_sises_web:
    resource: @SisesWebClientBundle/Resources/config/routing.yml