fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# Permite no exportar todas las rutas del fos_user
logout:
   path: /logout
   options:
       expose: true

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

concepto_pdf:
    path: /pdf/planilla/{id}/{date}.{_format}
    defaults:  { _controller: SisesApplicationBundle:PDF\PDF:planilla, _format: pdf }
    requirements:
        _format: pdf
    options:
        expose: true

concepto_sises:
    type: rest
    resource: @SisesApplicationBundle/Resources/config/routing.yml
    options:
        expose: true

concpeto_sises_web:
    resource: @SisesWebClientBundle/Resources/config/routing.yml

oneup_uploader:
    resource: .
    type: uploader
    options:
        expose: true

any:
    path: /{any}
    defaults:
        _controller: SisesWebClientBundle:Web:index
    requirements:
        any: .*

