security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Concepto\Sises\ApplicationBundle\Entity\Seguridad\Usuario:
            algorithm: sha256
            iterations: 100
            encode_as_base64: false

    role_hierarchy:
        ROLE_API: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN:
            - ROLE_USER
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    providers:
        concepto:
            id: concepto_sises_usuario.provider
        in_memory:
            memory:
                users:
                    user:
                        password: userpass
                        roles:
                            - ROLE_USER
                    admin:
                        password: adminpass
                        roles:
                            - ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            anonymous: true
            stateless: true
            provider: concepto
            simple-preauth:
                authenticator: concepto_sises_api.authenticator

    access_control:
        - { path: ^/api, roles: ROLE_API }
