empresa:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/EmpresaController.php
contrato:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/ContratoController.php
persona:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/PersonaController.php
beneficiario:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/BeneficiarioController.php
lugar_entrega:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/LugaresController.php
ubicacion:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/UbicacionController.php