empresa_publica:
    type: rest
    prefix: /api/empresas
    resource: @SisesApplicationBundle/Controller/Empresa/PublicaController.php
empresa:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/EmpresaController.php
contrato:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/ContratoController.php
servicios:
    type: rest
    parent: contrato
    resource: @SisesApplicationBundle/Controller/ServicioController.php
persona:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/PersonaController.php
beneficiario:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/BeneficiarioController.php
lugar_entrega:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/LugarController.php
ubicacion:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/UbicacionController.php
cargo:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/CargoController.php
encargado:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/EncargadoController.php
cargo_operativo:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/OperativoController.php
entidad_financiera:
    type: rest
    prefix: /api/financiera
    resource: @SisesApplicationBundle/Controller/Financiera/EntidadController.php
tipo_entidad_financiera:
    type: rest
    prefix: /api/financiera
    resource: @SisesApplicationBundle/Controller/Financiera/TipoController.php
rrhh:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/RecursoController.php
coordinador:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/Personal/CoordinadorController.php
director:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/Personal/DirectorController.php
admin_entrega:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/Entrega/EntregaController.php
coordinador_entrega:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/Entrega/AsignacionController.php
entrega_operacion:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/Entrega/OperacionController.php
servicio_operativo:
    type: rest
    prefix: /api/operativo
    resource: @SisesApplicationBundle/Controller/Personal/ServicioController.php
dashboard:
    type: rest
    prefix: /api
    resource: @SisesApplicationBundle/Controller/DashboardController.php
liquidacion:
    type: rest
    prefix: /api/entrega
    resource: @SisesApplicationBundle/Controller/Entrega/LiquidacionController.php